### PR TITLE
[WIP] Add QP interface through OSQP

### PR DESCRIPTION
**Pull request by cdiener**
This is a first working version of a QP solver via [OSQP](https://osqp.org). OSQP expects the problem to be sparse and static so I added a thin compatibility layer that manages the OSQP problem via dictionaries. All operations on that layer are at worst O(nv + nc) but it makes problem setup about 10-20% of the entire solve time for most models. Could maybe be optimized more in the future but should be sufficient for now. Still need to add tests but I added some more complicated models to the test data for now.

Demo:

```bash
Python 3.8.2 (default, Feb 25 2020, 13:04:52) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.13.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from optlang import osqp_interface as o                                                                                                                               

In [2]: import json                                                                                                                                                           

In [3]: qp = json.load(open("optlang/tests/data/QPLIB_8785.json"))                                                                                                            

In [4]: mod = o.Model.from_json(qp)                                                                                                                                           

In [5]: len(mod.variables)                                                                                                                                                    
Out[5]: 10399

In [6]: len(mod.constraints)                                                                                                                                                  
Out[6]: 11362

In [7]: mod.configuration.verbosity = 1                                                                                                                                       

In [8]: mod.configuration.tolerances.optimality = 1e-6                                                                                                                        

In [9]: mod.optimize()                                                                                                                                                        
-----------------------------------------------------------------
           OSQP v0.6.0  -  Operator Splitting QP Solver
              (c) Bartolomeo Stellato,  Goran Banjac
        University of Oxford  -  Stanford University 2019
-----------------------------------------------------------------
problem:  variables n = 10399, constraints m = 21761
          nnz(P) + nnz(A) = 73422
settings: linear system solver = qdldl,
          eps_abs = 1.0e-06, eps_rel = 1.0e-06,
          eps_prim_inf = 1.0e-06, eps_dual_inf = 1.0e-06,
          rho = 1.00e-01 (adaptive),
          sigma = 1.00e-06, alpha = 1.60, max_iter = 100000
          check_termination: on (interval 25),
          scaling: off, scaled_termination: off
          warm start: on, polish: on, time_limit: off

iter   objective    pri res    dua res    rho        time
   1   0.0000e+00   9.90e+01   9.90e+00   1.00e-01   8.20e-01s
 200   7.8676e+03   2.85e-02   2.36e-05   9.71e-04   3.86e+00s
 300   7.8675e+03   1.20e-04   1.53e-07   5.39e-03   5.40e+00s
plsh   7.8675e+03   8.53e-14   6.67e-10   --------   6.24e+00s

status:               solved
solution polish:      successful
number of iterations: 300
optimal objective:    7867.4911
run time:             6.24e+00s
optimal rho estimate: 5.55e-03

Out[9]: 'optimal'

In [10]: mod.objective.value  # reference solution: 7867.4911490000004051                                                                                                     
Out[10]: 7867.491148760175
```

One should note that this is a direct solver so it performs pretty bad for LPs or at very low tolerances. I added some optimizations for LP so it works ok-ish but worse than GLPK. However it is great for QPs so I think having a specialized solver for that is still helpful. 

# TODO

- [x] add tests
- [ ] add documentation
- [x] update deps?

### CODE REVIEW

**Comment by KristianJensen** [comment]
That is super cool :+1:. Regarding your question about tests on gitter: I don't think it would be a problem if the tests for this were done with pytest. However, with the current testing setup you would get most of the tests for a new interface for "free" by just subclassing the tests from `abstract_test_cases.py`, so that might still be easier.

I am not a pytest expert, but I would expect that it is possible to create a similar setup with pytest, where we can define tests for the common interface API and run them on all the solvers. If you know of a good way to do this and it is not a lot of extra work, it would be great if you implemented the OSQP tests using such a pattern in pytest.

**Comment by cdiener** [comment]
Okay, in the end I opted to continue with the `unittest` tests and did not use pytest features since the current setup would not be very pytest-onic. For pytest you would rather define a set of core tests and use `pytest.parametrize` to run them for each solver instead of using inheritance. I did have to reimplement most of the tests since (a) they assume the solver supports integer variables which OSQP does not and (b) they ignore the set solver tolerance and always evaluate accuracy against a tolerance of 1e-6 which OSQP can not achieve for *LP* problems. I also added two harder QP tests (4-10K variables) which still run in <10s. There is currently one skipped test that checks for correct pickling of the configuration which I can not figure out. Everything is pure Python objects so normal pickling should work but `interface` itself already overwrites `__setstate__` and I would need to reset that. AFAIK the appveyor tests fail because it tries to run all netlib test with GLPK excat solver without a bignumber library which will timeout the build.

**Comment by phantomas1234** [comment]
@cdiener this is really cool, thanks! @KristianJensen will you make a new release when this is in?

**Comment by KristianJensen** [comment]
@phantomas1234 Yes definitely. But there is still a technical issue that prevents us from merging into master. It seems that codecov just hangs forever, so GitHub blocks merging (e.g. #206). Could you maybe have a look at this?

**Comment by cdiener** [comment]
Okay, the config saving works now.

**Comment by cdiener** [comment]
Is there a reason that got closed?

**Comment by Midnighter** [comment]
I honestly have no idea how that happened. I certainly did not touch this PR through the interface... something is wrong with the branches though.

**Comment by Midnighter** [comment]
Sorry about this mess. I'm afraid you will have to recover your branch, which you should be able to with a single button push, before the PR can be reopened.

**Comment by cdiener** [comment]
Hm, looks like it deleted the branch from my repo. I'm surprised it had the permissions to do so. I found a version and will try to recover the branch. I changed laptops recently so I'm not sure whether it's the most recent version. Also the rebase is kind of a mess since the repo structure changed a lot. So I will leave it closed for now until I figure out a way to fix all of it.

**Comment by Midnighter** [comment]
You should be able to even to it right from the GitHub UI, I think. I guess you allowed edits from maintainers on the branch/PR. Still kind of surprising yes.

**Comment by cdiener** [comment]
I just pushed from a local branch. Looks okay but I'll need to check that I did not propagate old stuff in the rebase. I should be able to finish that bey the end of the week.

**Comment by Midnighter** [comment]
I'm sorry for the trouble :disappointed:

**Comment by cdiener** [comment]
No prob. It's more on Github in that case. Seems quite aggressive to delete the branch in another user's repo if the base branch gets merged.

**Pull request closed without merging**
